### ISSUE TITLE
Can't upload changes to Gerrit

### ISSUE THREAD

**Issue by kotzir** [TeamWin/android_device_samsung_expressltexx#1]
Uploading changes to Gerrit is not possible. Below is the output of my terminal. Thanks in advance
![expressltexx](https://cloud.githubusercontent.com/assets/7823010/14659665/902c624c-06a6-11e6-8e64-078eb93a517d.png)

**Comment by TeamWin-Gerrit** [comment]
Can you try now?

**Comment by kotzir** [comment]
Another issue occurs now.
![express](https://cloud.githubusercontent.com/assets/7823010/14695702/4ba2a6c2-077d-11e6-8570-f305ff968297.png)
